# Chapter 6 넘파이

#### http://www.numpy.org/

## 제1절 배열(array) 

## 1. 배열이란?

## 2. 배열 만들기 

### (1) np.array

In [5]:
import numpy as np

In [6]:
stock1=[15000, 14500, 16000, 17000]
arr1=np.array([stock1])
arr1

array([[15000, 14500, 16000, 17000]])

In [7]:
type(arr1)

numpy.ndarray

### (2) np.arange 

In [8]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1, 9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.arange(1, 30, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

## 3. 배열 탐색하기

### (1) shape : 배열 형태 확인하는 경우

In [11]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr.shape

(10,)

### (2) dtype : 배열 데이터 타입 확인하는 경우 

In [13]:
arr.dtype

dtype('int32')

### (3) astype : 배열의 데이터 타입 변경하기

In [37]:
arr1=arr.astype(str)
arr1

array(['1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U11')

### (4) 인덱스 범위 지정

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[4:7]

array([4, 5, 6])

In [17]:
arr[2]=20
arr

array([ 0,  1, 20,  3,  4,  5,  6,  7,  8,  9])

## 4. 배열 연산하기

In [18]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
arr-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
arr*10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
list= [1, 2, 3, 4, 5, 6, 7, 8, 9]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
list*10

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9]

In [24]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr1=np.arange(20,29)
arr1

array([20, 21, 22, 23, 24, 25, 26, 27, 28])

In [26]:
arr+arr1

array([21, 23, 25, 27, 29, 31, 33, 35, 37])

In [27]:
np.square(arr)

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [28]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [29]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [30]:
np.add(arr, arr1)

array([21, 23, 25, 27, 29, 31, 33, 35, 37])

In [31]:
np.sum(arr)

45

## 5. 배열 기초 통계량 

In [32]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.mean(arr)

5.0

In [34]:
np.std(arr)

2.581988897471611

In [35]:
np.max(arr)

9

In [36]:
np.min(arr)

1